languageCode: "en-us"
baseUrl: "http://imgios.github.io/thoughts/"
title: "💭 thoughts"
theme: "anubis"
paginate: 10
#disqusShortname: yourdiscussshortname
#googleAnalytics: UA-123-45
#enableRobotsTXT: true

menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 0
  - name: Archive
    title: Archive
    url: /posts/
    weight: 1

params:
  author: "Giosuè Sulipano"
  description: "A really micro static blog with my thoughts about stuff."
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
